### ISSUE TITLE
Reloading Crafttweaker causes it to generate a new set of the material instead of changing the old one

### ISSUE THREAD

**Issue by erindal** [The-Acronym-Coders/B.A.S.E#12]
![2016-09-20_18 14 02](https://cloud.githubusercontent.com/assets/12499779/18690797/0deae9da-7f5e-11e6-9635-62570f0fc416.png)

base-1.10-7-universal.jar
CraftTweaker-1.10.2-3.0.11.jar

Also the textures weren't generating, even with a restart, although I might be doing something wrong there.

Script:
mods.base.Materials.add("Uranium", 994590, false, ["ORE", "NUGGET", "INGOT", "BLOCK", "DUST"]);

**Comment by Lanse505** [comment]
Texture Issue: 
This is a known issue and something we're working on getting fixed (together with block implementation)

Duplication: 
Hmm, I'll have to poke Jared with this tomorrow when he wakes up.

**Comment by Lanse505** [comment]
We're looking into the issue of duplicate items.
I'll leave this post open until we get a concrete answer to why it's bugging out ^^

**Comment by Lanse505** [comment]
"Jared - Today at 10:06 PM
Ask him to retry without changing the scripts"

**Comment by erindal** [comment]
Okay, the script belongs in the _Minecraft Instance_/config/B.A.S.E/scripts folder, not the normal MT scripts folder.
