### ISSUE TITLE
uni-dict/b.a.s.e interaction

### ISSUE THREAD

**Issue by kurokuno** [The-Acronym-Coders/B.A.S.E#13]
version: B.A.S.E-1.0.0-1.10.2.jar

when uni-dicting all outputs to B.A.S.E and having it set to keep only one output type all smelting and grinding breaks also no base items are currently ore-dictionaried

**Comment by Lanse505** [comment]
We are taking steps to implementing OreDict on our things coming the next coming updates.
For now, there is a line in the Unidict config you need to use located between line 31-38.
