### ISSUE TITLE
Render Issue 

### ISSUE THREAD

**Issue by gigabit101** [The-Acronym-Coders/B.A.S.E#14]
https://github.com/The-Acronym-Coders/B.A.S.E/blob/Release/src/main/java/com/acronym/base/Base.java#L62 has to be in PreInit

**Comment by jaredlll08** [comment]
No it does not, if it is in preinit, the game crashes, I did this like 30
min ago.

What is the actual issue? Like game play wise?

**Comment by gigabit101** [comment]
Matt was telling me you where having issues with blocks so I had a look at the code and the first thing I saw was that line.
All of my mods get there models set in preInit otherwise they don't load for me

**Comment by jaredlll08** [comment]
Take a look at what that method actually does :P

It registers the json models etc, not the TESR models

**Comment by gigabit101** [comment]
yes I use jsons as well but I still have the issue if its not in preInit
