### ISSUE TITLE
Crash w/ Biomes You'll Go Mod

### ISSUE THREAD

**Issue by WenXin20** [The-Acronym-Coders/B.A.S.E#15]
1.10.2-Forge 2092
BASE V17
Crashes w/ the [Oh, the Biomes You'll Go Mod](https://minecraft.curseforge.com/projects/oh-the-biomes-youll-go-3?gameCategorySlug=mc-mods&projectID=247560) on game load
[Crash Log](http://pastebin.com/jF2eVMr0)

**Comment by jaredlll08** [comment]
ok so, this is 100% the other mod's fault, so the offending lines mentioned, according to a decompiled class is:
`GameRegistry.addSmelting(Blocks.field_150350_a, new ItemStack(block), 1.0F);`
that is a line in their mod, that translates to Blocks.AIR
they are doing some weird thing, not our fault, nothing We can do.

**Comment by WenXin20** [comment]
Ok, thanks, and I believe it was made using MCreator
I'll let the mod author know
