### ISSUE TITLE
Ore_ is dictionnaried with block_

### ISSUE THREAD

**Issue by demethan** [The-Acronym-Coders/B.A.S.E#17]
Hello guys,

Little probleme.  1.10.20 of BASE.  ore is dictionnaried with blocks. so you can craft an ore directly into 9 ingot..  OP much. lol 

Thanks
![2016-10-05_20 59 04](https://cloud.githubusercontent.com/assets/5810363/19136971/9db3eb52-8b3e-11e6-94e5-7ae535b41546.png)

**Comment by Lanse505** [comment]
Fixed Build 21
