### ISSUE TITLE
[Question and/or Feature Request] Question about the ore-gen base block texture

### ISSUE THREAD

**Issue by GazbonicAcid** [The-Acronym-Coders/B.A.S.E#19]
Is it possible to set the block texture used as a base for the ore generation?
If it isn't, I must request that you add this as a feature.
Setting the ore-gen for Advanced Rocketry custom planet xml has been added to their to-do list thanks to a post of mine.
Adding the ability to choose the base block texture would make it easier for pack authors (like me) to have their own custom planet with unique blocks.
The following probably belongs more in a full-out mod request somewhere else instead of being posted here, buuut...
I'd also like the ability to generate every type and kind of block and plant from vanilla through B.A.S.E.
I'm sure you can see why that last one belongs in a request for a separate mod.
So officially I'll just ask for the ability to set the base block texture for ore generation.
P.S. I need suggestions on how to get the appropriate int color number to generate an ore texture in a non-stone base with the same color and look as an ore from (another) mod/minecraft to help make it easier to customize ore-gen for Advanced Rocketry custom planets without the need to hard code it as a mod.

**Comment by Lanse505** [comment]
"changing the block texture used for ore generation"
It's on our todo list for the next major update.
No ETA at the current moment though.

**Comment by Lanse505** [comment]
/cc @SkySom 
Update?

**Comment by SkySom** [comment]
Next major update is 1.3, it'll be in 1.4

**Comment by belathus** [comment]
Man, I want this so bad. Especially for custom Advanced Rocketry planets, nether ores, and adding other ores to, for example, Railcraft's geodes.

**Comment by SkySom** [comment]
Yep this is pretty high on the todo list, along with fluids, it's one of the most asked for things. I'm trying to get it out as fast as possible

**Comment by SkySom** [comment]
Ready for 1.4.0 version coming this week
