### ISSUE TITLE
[Feature Request] Generate molten materials

### ISSUE THREAD

**Issue by TheAtomicOption** [The-Acronym-Coders/B.A.S.E#30]
This mod could use molten states for pipes, tanks, Tinker's Construct smelteries etc. 

Would require configurable melting temperatures, 
possibly a separate color value, 
bit for whether it's possible to place in the world with buckets (default: false)
A bit for whether it damages/burns players when placed in the world
a bit for whether it melts from torchlight like ice
a bit for whether it evaporates/explodes when placed in the nether like water

I'm not familiar with how TiC handles molten liquids so I'm not sure how big an ask this is, but it would be essential to using this mod as the ore generation base for lots of potential modpacks.

**Comment by Lanse505** [comment]
This is planned, however it's on the backburner in light of Univerity Exams.
We will get around to it but it isn't Prio 1 atm and there is and will be no ETA

**Comment by Lanse505** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tinkers](https://trello.com/c/NhtVzIuN/13-tinkers)

**Comment by Lanse505** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fluids](https://trello.com/c/R1704Les/26-fluids)

**Comment by SkySom** [comment]
Mostly finished, Will be in next release
