### ISSUE TITLE
Modular Utilities Crash

### ISSUE THREAD

**Issue by 63502** [The-Acronym-Coders/B.A.S.E#37]
I have no idea what this is, but it happens when I put the latest BASE in the same mod folder as the latest Modular Utilities.

[Crash Log](https://gist.github.com/63502/ba89fd1b181c73ae4ae9eae6b47c66fb)

[Crash Log w/ no other mods](https://gist.github.com/63502/99f2e19ec5555cb84cf3d1de158939fe)
 
These are the forge logs from the both the old and new base versions with nothing else loaded except modular utilities just in case the crash log isn't enough. Both logs have only base and modular utilities present.

[base-1.10.2-1.1.2](https://gist.github.com/63502/4e9c9180dde5d8aa67cdbe81d08b6993)

[base-1.10.2-1.2.0](https://gist.github.com/63502/a62e361e3852151eca8c6451c266d1b8)

**Comment by SkySom** [comment]
Yeah it's an MoU issue, fixing it now.

**Comment by SkySom** [comment]
https://minecraft.curseforge.com/projects/modularutilities/files/2366039 should be approved in a bit.

**Comment by 63502** [comment]
Ok, thanks. :)
