### ISSUE TITLE
Modular Utilities Crash again. :P

### ISSUE THREAD

**Issue by 63502** [The-Acronym-Coders/B.A.S.E#38]
I do not think the changes to MoU or BASE you made just now fixed the issue, this is still happening.

[Crash Log](https://gist.github.com/63502/43d5732ffe5d92e1b4cc1171cf9150d6)

[Crash Log w/ no other mods](https://gist.github.com/63502/d25033f3ea7b5e6f92ba21786830ff2c)

**Comment by SkySom** [comment]
Fixed one issue. But this is something else. BTW in the future these issues should go on MoU's tracker :D

**Comment by 63502** [comment]
Ok, sure. I just put it here because it seemed like the same thing as before.

**Comment by 63502** [comment]
Just opened a new issue on the MoU page.
