### ISSUE TITLE
Crash when using base version 1.2.1

### ISSUE THREAD

**Issue by misterfixit** [The-Acronym-Coders/B.A.S.E#39]
https://gist.github.com/misterfixit/ce52fba525533e3cffc1733c10f915ab

Will test with 1.2.2 tomorrow just making this for now

**Comment by SkySom** [comment]
Yep, update to 1.2.2 of BASE and 0.4.2 of Modular Utilities and it should be fixed.

**Comment by misterfixit** [comment]
Modular utilities isn't even in the instance

**Comment by Lanse505** [comment]
@misterfixit think that's just for reference since Modular Utilities also had a similar issue

**Comment by SkySom** [comment]
It's called I have my head up my ass and didn't read that it's BASE throwing the error... ModularUtilities had the same one and I thought it was that...

**Comment by Lanse505** [comment]
Yes @SkySom We know you like buttstuff jeez ;P

**Comment by SkySom** [comment]
According to misterfixit, seems it has mostly resolved itself, also added more specific logging in hopes that if this reappears we have more information.
