### ISSUE TITLE
I'm back with yet another MoU and BASE crash.  (╯°□°）╯︵ ┻━┻)

### ISSUE THREAD

**Issue by 63502** [The-Acronym-Coders/B.A.S.E#40]
BASE and MoU are at it AGAIN. 
These two mods really do not like each other.
They just don't.

[Crash Log](https://gist.github.com/63502/2e7eecd7d3f3e35d429e0bd44652db15)

Base version: 1.2.2

MoU version: 0.4.2

**Comment by SkySom** [comment]
The next time I think, I should really rewrite the internals of a major section of code. Someone point me to all the issues this time caused.

**Comment by SkySom** [comment]
http://ci.blamejared.com/job/BASE-Release/39/artifact/build/libs/base-1.10.2-1.2.3.jar 
Try this build. I've done a lot more null checking.

**Comment by 63502** [comment]
> Try this build. I've done a lot more null checking. -SkySom

I'm sorry, but I think BASE disagrees.

[Crash Log](https://gist.github.com/63502/ca7c55ffd70ef29855855b97a471a107)

**Comment by SkySom** [comment]
http://ci.blamejared.com/job/BASE-Release/40/artifact/build/libs/base-1.10.2-1.2.3.jar
Yeah MoU is throwing shit at BASE. I'm gonna have to take a closer look, but for some reason it works in dev, do you have anything configured to be off? But try the new build, it's the last thing I can think to null check.

**Comment by 63502** [comment]
This build actually works. My game did not crash on startup, and everything seems to be running ok.

**Comment by SkySom** [comment]
Should be on curse in a bit. Thanks for all the reports!
