### ISSUE TITLE
[Suggestion] Filtered Ore Dict Dump

### ISSUE THREAD

**Issue by ChloeDawn** [The-Acronym-Coders/B.A.S.E#42]
A command or something similar that allows the user to dump a list of filtered ore dictionary entries matching `ore`, `ingot`, `plate` etc. to a file in the BASE config directory, for use as a reference when making scripts.

**Comment by SkySom** [comment]
Good idea

**Comment by Lanse505** [comment]
/cc @jaredlll08 
Isn't there something like this in Minetweaker?
If not shouldn't there be >.>?
Worst case it'd be a nice feature either way to have in BASE for debug purposes.

**Comment by belathus** [comment]
There is an unfiltered oredictionary dump via "/mt oredict". An example of such a dump is here: https://github.com/belathus/Wanderlust-Renewed/blob/master/oredict

**Comment by SkySom** [comment]
Honestly not really worried about making this happen. Could also add some matching stuff to the CraftTweaker command.
