### ISSUE TITLE
BASE hiding custom crafttweaker recipes in JEI?

### ISSUE THREAD

**Issue by SeriousCreeper** [The-Acronym-Coders/B.A.S.E#43]
Heyo, 

i noticed recently that the custom recipes i added to the embers melter (and other machines) don't show up in JEI properly when i add BASE to the pack. The recipes i set up still work, but JEI doesn't display them properly. As soon as i disable BASE, it shows up properly again. 

Example of what i'm trying:
```
mods.embers.Melter.remove(<liquid:iron>);
mods.embers.Melter.addOreRecipe(<ore:nuggetIron>, <liquid:iron> * 99, false, false);
```

Melter is suppose to remove everything iron related and only melt a nugget into 99mB of molten iron. 
The recipe works, but JEI now shows that a nugget still melts into 16, it also shows the recipe for the ingots and ore blocks (that should be removed). 

If i remove BASE, the only recipe i see is the one specified above. 

I tried to move my custom recipes into the BASE/scripts folder too, to see if that makes a difference, but doesn't seem to. 

If i disable "Materials enabled" in the config, it works properly, but then i don't have any materials of course heh. 

Any idea how to fix this? 

Possible an issue with embers (@elucent) itself? (Gonna see if i can replicate this with other mod recipes) 

EDIT: yeah same happens with tinkers recipes such as this:

```
mods.tconstruct.Smeltery.addMelting(<liquid:copper> * 99, <embers:nuggetCopper>, 200, <embers:nuggetCopper>);
```

Thanks,
SC

**Comment by SkySom** [comment]
I'm gonna assume its not Materials, its the Minetweaker module, and how we have to run our scripts early. Try turning that off.

**Comment by SeriousCreeper** [comment]
Thanks for getting back so quickly!

Tried to disable the Minetweaker module, but didn't make any difference. Also tried the JEI one to check, also no difference.

**Comment by SkySom** [comment]
Interesting. The Minetweaker one is the only one that actual loads minetweaker. Guess it comes down to mod load order. Interesting. Will remove that in a bit and see if that majes it work for you.

**Comment by jaredlll08** [comment]
What JEI, MTLib, Crafttweaker, Modtweaker versions are you running?

**Comment by SeriousCreeper** [comment]
JEI: 3.14.6.408
CT: 3.0.20
MT: 2.0.9
MTLib: 1.0.1

**Comment by jaredlll08** [comment]
This may seem like a weird request, but can you remove Base and add initial inventory please, you don't need to add any scripts, I'm just testing a theory

**Comment by SeriousCreeper** [comment]
Just tried it out, same thing indeed! Recipe is working but not showing up in JEI.

**Comment by jaredlll08** [comment]
Could you pass me your minetweaker.log file, and the game log file please

**Comment by SeriousCreeper** [comment]
Sure,
minetweaker.log: http://pastebin.com/Nk6uMQWa
fml-client-latest.log: http://pastebin.com/qSe7s0Ze 

Let me know if you need a different kind of log or anything. 

Thanks,
SC

**Comment by jaredlll08** [comment]
Do me a favour and try this version
http://ci.blamejared.com/job/CraftTweaker-Dev/12/
And I will need the game log and the minetweaker.log file please

**Comment by SeriousCreeper** [comment]
Unfortunately no difference. 

Minetweaker.log: http://pastebin.com/kB5rFRZk
client log: http://pastebin.com/r1favpVx

**Comment by jaredlll08** [comment]
kk cool, so these shouldn't actually fix anything, it is just giving me more debug info to try and figure this issue out
http://ci.blamejared.com/job/CraftTweaker-Dev/13/
I would need the same info please

**Comment by SeriousCreeper** [comment]
Gotcha! 

Minetweaker: http://pastebin.com/tbxFB9S4
Client: http://pastebin.com/mgnbzgCQ

**Comment by jaredlll08** [comment]
Ok so, nearly there, this one should give me a lot more info about this issue!
http://ci.blamejared.com/job/CraftTweaker-Dev/14/

Sorry for asking you to do all of these >_< I just can't reproduce it on my side :/

**Comment by SeriousCreeper** [comment]
No problem! Glad to help out, let me know if you need more testing. 

Minetweaker: http://pastebin.com/9vWKYzcm
Client: http://pastebin.com/NjjaWft0

**Comment by jaredlll08** [comment]
Can you update to the latest CrT and try again please

**Comment by SeriousCreeper** [comment]
Sorry for the late reply, just gave it a try, unfortunately still doesn't show the correct recipe.

Minetweaker; http://pastebin.com/YN9Sfmee
Client: http://pastebin.com/6tFJDY40 

Let me know if you need more testing!

Cheers,
SC

**Comment by Lanse505** [comment]
@jaredlll08 ???

**Comment by jaredlll08** [comment]
I honestly have no idea on this

**Comment by SkySom** [comment]
Shouldn't be an issue in 1.12 (Can't really figure it out in 1.10 so it just has to be a thing, sorry!)
