### ISSUE TITLE
[REQUEST] Dense Plate

### ISSUE THREAD

**Issue by bookerthegeek** [The-Acronym-Coders/B.A.S.E#46]
Hello again!

I formally request an additional item, a Dense Plate. No recipe should be needed for it, as modpack authors can Craft Tweaker one in for it depending on the mods installed in the pack.

**Comment by SkySom** [comment]
Seems doable, though what exactly should a dense plate look like?

**Comment by SkySom** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dense Plate](https://trello.com/c/IrmfWroP/48-dense-plate)

**Comment by bookerthegeek** [comment]
Personally I like the one from [magneticraft](https://github.com/Magneticraft-Team/Magneticraft/tree/kt1.9/src/main/resources/assets/magneticraft/textures/items/heavy_plate), although [IC2](http://ftb.gamepedia.com/Dense_Plates_(IndustrialCraft_2)) has some desent textures as well.

**Comment by SkySom** [comment]
WIll be in the next 1.11.2 release

**Comment by bookerthegeek** [comment]
Thank you!
