### ISSUE TITLE
B.A.S.E ores do not work in Thermal Expansion machines

### ISSUE THREAD

**Issue by GeoRCCraft** [The-Acronym-Coders/B.A.S.E#47]
Well, to be honest, the title says it all. By default, B.A.S.E ores will not work in Thermal Expansion machines.

**Comment by SkySom** [comment]
Of course TE wouldn't just take oredict stuff and handle it on their own... Will take a look when I get time.

**Comment by Lanse505** [comment]
Talked it over with both Covers of the TE team and with Sky.
Turns out it does "auto-register" recipes however we are at fault here due to us registering oredicts in init rather than preInit.

This is getting fixed!

**Comment by SkySom** [comment]
Fixed in 1.3 (On curse already)
