### ISSUE TITLE
[BUG] Registereds material not showing in 1.3.0

### ISSUE THREAD

**Issue by Slater022** [The-Acronym-Coders/B.A.S.E#48]
![image](https://cloud.githubusercontent.com/assets/3940371/24874474/1b3e9512-1e25-11e7-8b14-056c57a6b59e.png)

Material.zs : 
import com.acronym.base.IMaterialType;

var osmium = mods.base.Materials.getOrRegister("osmium", 20, 9090A3, false);

osmium.registerNugget();
osmium.registerIngot();
osmium.registerDust();
osmium.registerGear();
osmium.registerPlate();
osmium.registerOre(3, 15, "pickaxe", 3);
osmium.registerPoorOre(3, 15, "pickaxe", 3);
osmium.registerBlock(5, 30, "pickaxe", 3);

**Comment by Slater022** [comment]
But showing when i do a research 
![image](https://cloud.githubusercontent.com/assets/3940371/24874521/3dd40a9e-1e25-11e7-9cf3-ab98548bf46d.png)

**Comment by SkySom** [comment]
Should be fixed both for V1 and V2 of the Material System
