### ISSUE TITLE
Iron gear is missing.

### ISSUE THREAD

**Issue by Claycorp** [The-Acronym-Coders/B.A.S.E#50]
I enabled the iron option in the config 
``  # Should Iron be registered as a material?
 B:Iron=true ``
It gives me all the other iron stuff (Plate and dust) but does not give a gear.
![image](https://cloud.githubusercontent.com/assets/3961359/24884487/3614edd4-1e0f-11e7-8ccf-ebbf4fb42487.png)

Edit I should include a version also duh... 1.3.0

**Comment by Slater022** [comment]
Can I see your config ? i'll try in my side :)

**Comment by SkySom** [comment]
Plate, dust, and nugget are all we register for Iron (Expected Behavior), but I don't see why we can't add the gear in.

**Comment by Claycorp** [comment]
I just assumed that there would be a gear as everything else had a gear except iron.
Thanks for adding it!

**Comment by Lanse505** [comment]
Originally we discussed having the Iron Gear be part of the Iron Set.
However there were some worry early on about the iron having too big of an overlap with other mods such as CoFH and BC. 

However tbh thinking back at it, it was a mute point, so yea this could certainly be added as a 1.3.1 enhancement.
