### ISSUE TITLE
Additional Default Materials

### ISSUE THREAD

**Issue by bookerthegeek** [The-Acronym-Coders/B.A.S.E#52]
## Heyo ##
I've notices the default materials you have included, I was wondering if you have plans to include other common materials as built in defaults? Specifically materials Added by more then one mod would be my way of thinking?
 - Invar
 - Steel
 - Bronze
 - Electrum

Thanks again for the amazing mod. :)

**Comment by SkySom** [comment]
Nope. In fact with the rewrite of the material system we are removing the defaults. It'll be completely up to the user to add them ( I do however plan to publish a script on the wiki that would still give those)

**Comment by bookerthegeek** [comment]
Understandable. Thanks for the response.
