### ISSUE TITLE
Is the 1.11.2 branch working ?

### ISSUE THREAD

**Issue by fangedhex** [The-Acronym-Coders/B.A.S.E#53]
Hello,

I saw you made your mod for 1.11.2 (if we build it ourselves).
But it doesn't work, I tried the example script on the wiki, I put it in the right directory but nothing is added ingame except the wrench...

I want to know if that's normal ? Because I try to find a mod to unify all the ore(+stuff) mods but only your mod is able to do all ores I need ( others unifier miss 1 or 2 ores ).

Thanks for your answer :)

**Comment by Lanse505** [comment]
1. From 1.11.2 onward you'll need both ContentTweaker and BASE to add content.
2. Not sure if the 1.11.2 branch of either BASE nor ContentTweaker is done yet :P 

@SkySom might have more information, but TLDR; We're not ready for a 1.11.2 release either for testing or public use last I checked.

**Comment by fangedhex** [comment]
Yup, I saw that ContentTweaker doesn't have any 1.11.2 related branch or commit :(
As I can't go back to 1.10.2, I'm gonna try to find something else to do what I want :/

**Comment by SkySom** [comment]
There is a branch for 1.11 but there is no code on that branch. Its currently a copy if the 1.10. Branch. Its coming soon, but no eta

**Comment by SkySom** [comment]
Oh wait, I just realized this isn't on the Content Tweaker Repo. Yes. BASE does have full 1.11 version (Which is basically ready for release on Curse), however yes, in 1.11, the only way to use BASE for modpacks will be via Content Tweaker (All the Zenscript api stuff was moved to make it easier to maintain scripts in one place, instead of two)

**Comment by fangedhex** [comment]
I can wait, my modpack is still WIP until I have all the mods I need :)
Just one question : did you start working on 1.11.2 or not ? It's just to have an idea of what I gonna do on my modpack !

**Comment by SkySom** [comment]
BASE is fully done on 1.11.2, and ContentTweaker shouldn't be an awful port once I get time. (The delay on these two were more due to wanting to get certain features in the 1.10.2 version before the port, which these are now in)

**Comment by fangedhex** [comment]
I tried to "update" myself but I'm not experimented as forge modder :/ Also I love the way you make BASE that we can make any type of metals we want :D

**Comment by SkySom** [comment]
It's quite alright! I'm going to try today to get a beta out perhaps. Though I'm not sure what you mean by make any type of metal? Feel free to jump into discord https://discord.gg/QW8fr6u and explain

**Comment by fangedhex** [comment]
I means about having template and then we can add all sort of metal we want with just a color :P 
If you have a beta, I can try it out and give you feedback ! I'm also now on your Discord so I can checkout things there :)

**Comment by SkySom** [comment]
Can check out the builds on Jenkins: http://ci.blamejared.com/job/ContentTweaker/job/develop%252F1.11.2/ will also need the newest BASE off the jenkins too
