### ISSUE TITLE
Suggestion -- Gravel ores / sandy ores

### ISSUE THREAD

**Issue by OrdinatorStouff** [The-Acronym-Coders/B.A.S.E#54]
I love the modular nature of BASE and the ability to register/add new ores/ingots/etc

I would love to be able to also use this same infrastructure to implement nihilo-style "ore gravel" (and "ore sand" too if that's not too crazy to consider) as well as the intermediary pieces like "ore chunks" and "ore pieces"

If all of that is too much bloat to add then the one thing I think would still be neat at least is the "ore gravel" part. There are already some mods that add ore gravels but they lack the dynamic nature of BASE and it would be cool to be able to "unify" all these types to all be from the same mod.

**Comment by Lanse505** [comment]
Gravel/Sand/anything ores is possible in the new system of BASE/ContentTweaker in 1.11.

**Comment by SkySom** [comment]
As Lanse said, the new Materials system in ContentTweaker (Which is a new version of teh one in BASE) in 1.10 allows for adding texture variants. (See https://github.com/The-Acronym-Coders/ContentTweaker/wiki/Materials-V2-Test for an example which also adds netherrack and end stone versions)

**Comment by Lanse505** [comment]
Yea, I'm talking about it with them in their private discord.
Gonna be closing this thread.

**Comment by SkySom** [comment]
And can also be used by modpack makers to create their own new parts (Like the ore pieces) which work along side the pieces added by BASE/Contenttweaker themselves. However I can look at adding some new support for ExNihilo in 1.11?
