### ISSUE TITLE
B.A.S.E Dusts Don't Melt In Tinkers' Construct Smeltery?

### ISSUE THREAD

**Issue by RogueRaiden** [The-Acronym-Coders/B.A.S.E#56]
Alright, I have added B.A.S.E into my modpack and it looks like the dusts dont melt in the Tinkers Construct Smeltery? I could very well be missing something, but in the B.A.S.E configs i enabled most of the metals (you know, trying to use the mod for its intended purpose lol) and didnt see anything in the Tinkers configs.

**Comment by SkySom** [comment]
Are there molten versions of the metal already? BASE currently doesn't add liquids, its next on the priority list.

**Comment by RogueRaiden** [comment]
Yeah, getting the thermal expansion versions of the ore, dust or ingot produces the liquid metal in the smeltery just fine. Actually now that i think about it, the BASE version of the ingot may actually smelt. But I'll have to wait until i get home to test.
Also, since im here, is there plans to make it a config option to drop the BASE version of an ore regardless of the ore mined? Useful for people that want all the ore to be from a single mod, and/or when a lot of mods add the same type of ore. (There was a mod that did this in 1.7.10 and i couldn't find one, seems like it would be a good fit here)

**Comment by SkySom** [comment]
I'd be willing to consider it as an opt in solution

**Comment by RogueRaiden** [comment]
well, im not quite sure what happened but everything from BASE works just fine.
And im sorry, but what do you mean with "an opt in solution"?

**Comment by SkySom** [comment]
Basically a config that defaults to false, but that one could turn on to force other ores to drop base versions

**Comment by RogueRaiden** [comment]
that would be really cool, just as an option for people who want to clean up their ores a bit without having to reset their world. Going to close the issue though, since it isn't happening.
