### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by AndreiTS** [The-Acronym-Coders/B.A.S.E#58]
I don't knowm what I am doing wrong. If I set to true in the config file nothing happens, and if a use a script it crashes. (tried .json, .zs) used the example in the wiki

**Comment by SkySom** [comment]
Version? Logs?

**Comment by AndreiTS** [comment]
I found what is causing problems.  This mods here: https://minecraft.curseforge.com/projects/unidict

version: 1.10.2

**Comment by SkySom** [comment]
So yeah, not much I can do, if you have a mod that specifically replaces stuff...
