### ISSUE TITLE
Changing blockstates texture path not working.

### ISSUE THREAD

**Issue by chadmcn** [The-Acronym-Coders/B.A.S.E#66]
Changing the path for the texture to set custom textures for all my ores does not work at all. 

This is the changed .json from blockstates: 
https://pastebin.com/ik52qsu9

And heres the log:
https://pastebin.com/3vjsVK2p

**Comment by SkySom** [comment]
Your log says saying using missing texture, can't find contenttweaker: and then gives the rest of the path you use

**Comment by chadmcn** [comment]
Alright, messed around and got it to work but now there's something else weird happening. The cracks from when you mine it look really wrong. 

![screenshot_1](https://user-images.githubusercontent.com/20251583/30517918-dd162624-9b33-11e7-973a-abc0629a0223.png)

![screenshot_2](https://user-images.githubusercontent.com/20251583/30517919-df2483c0-9b33-11e7-893e-7061fc12085c.png)

**Comment by FreneticScribbler** [comment]
(Herro, housekeeping)

The cracks look alright to me. If you insist, open a new issue.
