### ISSUE TITLE
Requirements for creating custom materials

### ISSUE THREAD

**Issue by Chenjox** [The-Acronym-Coders/B.A.S.E#68]
I am a bit confused with this mod and i am unable to find proper documentation.

I created a script as described in the wiki and copy-pasted it and replaced the variable name.
But when i start up the game, no custom materials can be found.

Do you need ContentTweaker for implementing custom materials?

Using:
Minecraft Version: 1.12.2
Forge: forge1.12.2-14.23.0.2486
BASE: 3.3.0

Also Using:
Binnie-Mods
Calculator
CommonCapabilities
Crafttweaker
Cucumber
CyclopsCore
Forestry
Forgelin
HardcoreDarkness
Industrialforegoing
IntegratedDynamics & Tunnels
JEI
mcjtylib
mysticalagriculture
QuantumStorage
RebornCore
refinedstorage
rftools
sonarcore
Techreborn
tesla-core-lib

Thank you in advance
Chenjox

**Comment by SkySom** [comment]
As of 1.12, yes you need ContentTweaker for implementing Custom Materials.

The new script that can be used as an example for this can be found in ContentTweaker's WIki.

**Comment by Chenjox** [comment]
As a suggestion: I would notice my audience about the now necessary ContentTweaker on the libaries site to counteract confusion.

Thank you for your help

**Comment by SkySom** [comment]
Correct. This is a really new change so we're still in process of making sure the documentation gets updated!
