### ISSUE TITLE
Block part naming

### ISSUE THREAD

**Issue by pyure** [The-Acronym-Coders/B.A.S.E#74]
Per discussion with SkySom:

Create a block requires MaterialSystem.getPartType("storage") .

One might logically expect MaterialSystem.getPartType("block") here (notwithstanding that it kinda visually conflicts with something like metal.registerPart("block"), not really a problem. )

Connected, you identified this as a concern:
var machineFrame = MaterialSystem.getPartBuilder().setName("machine_frame") 
 vs 
var machineFrame = MaterialSystem.getPartBuilder().setName("Machine Frame")

**Comment by SkySom** [comment]
Fixed by: https://github.com/The-Acronym-Coders/BASE/commit/1c633105e5f381a3031a7f278a7f4648cc339a5d
