### ISSUE TITLE
Block model default

### ISSUE THREAD

**Issue by pyure** [The-Acronym-Coders/B.A.S.E#75]
When building an object of partType "block" (Ahem storage), the texture defaults to the same used for the metal block texture.

**Comment by pyure** [comment]
var machineFrame = MaterialSystem.getPartBuilder().setName("machine_frame").setPartType(MaterialSystem.getPartType("storage")).build();

**Comment by SkySom** [comment]
Fixed by: https://github.com/The-Acronym-Coders/BASE/commit/1c633105e5f381a3031a7f278a7f4648cc339a5d
