### ISSUE TITLE
Geolosys Samples

### ISSUE THREAD

**Issue by Lanse505** [The-Acronym-Coders/B.A.S.E#78]
Please Add Geolosys Samples

KThx

https://github.com/oitsjustjose/Geolosys/blob/master/src/main/resources/assets/geolosys/blockstates/ore_sample.json
https://github.com/oitsjustjose/Geolosys/blob/master/src/main/resources/assets/geolosys/blockstates/ore_sample_vanilla.json
https://github.com/oitsjustjose/Geolosys/blob/master/src/main/resources/assets/geolosys/models/block/sample.json

No idea about the texture location though 🤔

**Comment by SkySom** [comment]
Just need a block with the shape of the Geolosys blocks, nothing else.
