### ISSUE TITLE
Large numbers of Materials items appears to break JEI search

### ISSUE THREAD

**Issue by pyure** [The-Acronym-Coders/B.A.S.E#85]
SkySom this is primarily a reminder-ticket of our conversation.

I'm encountering a problem where my material parts stop appearing in JEI Search when I have hundreds of them.  

They (seem to) still show up in Creative search, and _may_ show up when drilling recipes for and usages of these items.

You've proposed the following:

> I think I need to do the fix I've been speaking of for a while and break things down into multiple items.
> But basically I'd add a max per item config item
> so basically you'd say "max = 250", ids 251 ->500 would end up on material_part_2

**Comment by SkySom** [comment]
This is all fixed up and released fivever ago. Two fixes here:

Fix 1) Go into your JEI config and up the number of subitems to show
Fix 2) If you can afford world breaking go into the materialsystem config and turn max size down to 1
