### ISSUE TITLE
Variant base texture invisible

### ISSUE THREAD

**Issue by justinrusso** [The-Acronym-Coders/B.A.S.E#90]
Remember that issue I ran into, but appeared like no one else had it? Well... not anymore :(

https://github.com/Darkosto/SevTech-Ages/issues/624

**Comment by justinrusso** [comment]
`resources/contenttweaker/blockstates/materials/aquamarine_ore_minecraft_stone.json`:
```JSON
{
  "forge_marker": 1,
  "defaults": {
    "transform": "forge:default-block",
    "model": "base:ore",
    "textures": {
      "particle": "minecraft:blocks/stone",
      "texture": "minecraft:blocks/stone",
      "ore": "base:blocks/ore",
      "ore_shadow": "base:blocks/ore_shadow"
    }
  },
  "variants": {
    "normal": [
      {}
    ],
    "inventory": [
      {}
    ]
  }
}
```

**Comment by justinrusso** [comment]
Worth noting, this appears to only be happening with the `minecraft:blocks/stone` texture. I have a few ores for other textures than stone, and they are all from other mods, and those display fine.

**Comment by Buuz135** [comment]
Have you tried `blocks/stone` instead?

**Comment by justinrusso** [comment]
Well, this is how its generated. I can give that a try though. The particle works fine.

**Comment by justinrusso** [comment]
Didn't make a difference

**Comment by justinrusso** [comment]
Copying over the options.txt, configs, resources, mods, and the necessary scripts to create the CoT blocks seems to not have the issue..

**Comment by SkySom** [comment]
Turns out it's an issue on another mod who is changing how the Stone texture works
