### ISSUE TITLE
Crash when attempting to drop invalid item

### ISSUE THREAD

**Issue by Gegy** [The-Acronym-Coders/B.A.S.E#95]
From: https://github.com/gegy1000/PracticalSpaceFireworks/issues/5

When an invalid item is specified, this code prints an error, but allows the code to continue:
https://github.com/The-Acronym-Coders/BASE/blob/0244cd5c37a47dab9efdd6778be2f9e4c80fc165/src/main/java/com/teamacronymcoders/base/materialsystem/blocks/SubBlockOrePart.java#L60-L64

Leaving this code to crash, as isValid does not check for null:
https://github.com/The-Acronym-Coders/BASE/blob/0244cd5c37a47dab9efdd6778be2f9e4c80fc165/src/main/java/com/teamacronymcoders/base/materialsystem/blocks/SubBlockOrePart.java#L70-L74

**Comment by FreneticScribbler** [comment]
I think https://github.com/Brian-Wuest/MC-Prefab/issues/84 is the same issue?

**Comment by SkySom** [comment]
It is most likely, yes
