### ISSUE TITLE
Updating from 3.7.2 to 3.8.0 causes a crash during initialization when Immersive Engineering is installed

### ISSUE THREAD

**Issue by MrMetric** [The-Acronym-Coders/B.A.S.E#96]
I am using Forge 14.23.4.2707 (current latest) and Immersive Engineering 0.12 - 82 (current latest from CurseForge). Here is the stack trace: https://openeye.openmods.info/crashes/a44424143274e07a6ebb75d4501f22bd. The code responsible for the crash was added in commit 947b7144f6970465f7cd3d76095cd18011ac2b98.

**Comment by SkySom** [comment]
Disable the Tool module. It will fix it for now.

**Comment by Zarthong** [comment]
Have the same issue

**Comment by Mattabase** [comment]
Disabling Tool module is a workaround indeed. =)

**Comment by SkySom** [comment]
Fixed and on Curse
