### ISSUE TITLE
Issue with null pointer

### ISSUE THREAD

**Issue by Zarthong** [The-Acronym-Coders/B.A.S.E#97]
https://pastebin.com/ksNVGMus may be a journey map issue, will submit there as well, no game crash, just cannot interact with the world, blocks don't drop, redstone does not activate, GUIs are inaccessible, right clicking with tools does not use them (if it should)

**Comment by SkySom** [comment]
There's nothing in that mentions this mod at. The base stuff is Google's library. This is all Journey map
